# The URL where your site will be live
base_url = "https://aliHOZA.github.io"
title = "مدونتي الجديدة" # "My New Blog" in Arabic
description = "مدونة شخصية بتصميم عصري ودعم RTL."

# The theme to use
theme = "tabi"

# --- IMPORTANT RTL SETTINGS ---
# Set this to true to enable Right-to-Left support
rtl = true
# Set the primary language code for your content
language_code = "ar" # Use "ar" for Arabic, "fa" for Persian, "he" for Hebrew

# Generate a feed for your posts
generate_feeds = true

# Taxonomies for organizing content
taxonomies = [
    {name = "tags", feed = true},
    {name = "categories", feed = true},
]

[markdown]
# Enable smart punctuation
highlight_code = true
highlight_theme = "css"

[extra]
# These are settings specific to the 'tabi' theme
# Put the links to your social profiles here
author = "aliHOZA"
links = [
    { name = "GitHub", href = "https://github.com/aliHOZA" },
    # { name = "Twitter", href = "#" },
]
