baseURL = "https://username.github.io/"
languageCode = "en-us"
title = "My Weblog"
theme = "hugo-theme-relearn"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
  themeVariant = "relearn"
  themeVariantAutoSwitch = false

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10

[params]
  editURL = "https://github.com/username/username.github.io/edit/main/content/"
  showVisitedLinks = true
  disableBreadcrumb = false

  [params]
  customLogo = "/images/IranDirectory.png"
